# Copyright (c) 2023 Tim <tbckr>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

# https://taskfile.dev

version: '3'

tasks:
  setup:install:
    desc: Install devtools
    preconditions:
      - which python3
      - which go
    cmds:
      - pip3 install --user --upgrade pre-commit
      - pip3 install --user --upgrade commitizen
      - go install github.com/google/addlicense@latest

  setup:validate:
    desc: Validate that all necessary devtools are installed
    cmds:
      - which go 1>/dev/null || (echo "go is not installed" && exit 1)
      - which python3 1>/dev/null || (echo "python3 is not installed" && exit 1)
      - which pre-commit 1>/dev/null || (echo "pre-commit is not installed" && exit 1)
      - which addlicense 1>/dev/null || (echo "addlicense is not installed" && exit 1)
      - which cz 1>/dev/null || (echo "cz is not installed" && exit 1)

  setup:hooks:
    desc: Setup git hooks
    preconditions:
      - which pre-commit
    cmds:
      - pre-commit install

  setup:
    desc: Setup development environment
    aliases:
      - "s"
    cmds:
      - task: setup:hooks

  license-header:
    desc: Add license header to all files
    aliases:
      - "license"
    cmds:
      - |
        addlicense -c "Tim <tbckr>" -l MIT -s -v \
        -ignore ".idea/**" \
        -ignore ".task/**" \
        -ignore "**/remote-src/**" \
        .

  lint:md:
    desc: Lint markdown files
    cmds:
      - docker run --rm --pull always -v $(pwd):/app:ro ghcr.io/tbckr/markdownlint:18 . --config=.mdl_config.yaml

  lint:
    desc: Lint all files
    cmds:
      - task: lint:md

  submodule:update:
    desc: Update submodules
    cmds:
      - git submodule update --init --recursive --force

  build:all:
    desc: Build all docker containers
    cmds:
      - ./build-all.sh

  ci:
    desc: Run CI pipeline
    cmds:
      - task: test

  test:
    desc: Run tests
    cmds:
      - ./test.sh